#!/bin/bash
#
# stagecaptionfiles:		Send captions from files (for demo/test)
#
# chkconfig:	345 120 10
# description:	Reads saved closed captions from files
#		and sends the parsed results to a service
#		to process the data for Flip.TV
#

# Source function library.
. /etc/rc.d/init.d/functions

export CONFIG=stage

FLIPTV_HOME=/usr/local/flip.tv/$CONFIG
[ -d $FLIPTV_HOME ] || exit 0

SERVICE=${CONFIG}captionfiles
export APPNAME=SendCaptionFiles
export CONFIG_FILE=/etc/flip.tv/${SERVICE}.xml

start() 
{
	echo -n $"Starting ${SERVICE}: "
	daemon $FLIPTV_HOME/runchannelfeed $FLIPTV_HOME

	touch /var/lock/subsys/${SERVICE}
	echo
}

stop() 
{
	echo -n $"Shutting down ${SERVICE}: "
	killproc $CONFIG-$APPNAME

	rm -f  /var/lock/subsys/${SERVICE}
	echo
}

# See how we were called.
case "$1" in
  start)
	start
        ;;
  stop)
	stop
        ;;
  restart|reload)
	stop
	start
	;;
  condrestart)
	[ -e /var/lock/subsys/${SERVICE} ] && (stop; start)
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|reload|condrestart}"
	exit 1
esac

exit 0
